version: '3'

services: 
   blazegrapheds:
    image: lyrasis/blazegraph:2.1.4
    container_name: ${BLAZEGRAPH_CONTAINER_NAME}
    volumes:
      - ./data:/data
    ports:
     - ${BLAZEGRAPH_PORT}:8080
    environment: 
     - JAVA_XMS=${JAVA_XMS}
     - JAVA_XMX=${JAVA_XMX}
    env_file:
      - ./.env
   
   ontodia:
    build:
     context: ./ontodia
    image: ontodia:1.0
    container_name: ontodia
    ports: 
     - ${ONTODIA_PORT}:${ONTODIA_PORT}
    depends_on:
     - ${BLAZEGRAPH_CONTAINER_NAME}
    environment: 
      - SPARQL_ENDPOINT=http://${BLAZEGRAPH_CONTAINER_NAME}:8080/bigdata/namespace/${BLAZEGRAPH_NAMESPACE}/sparql
      - PORT=${ONTODIA_PORT}
    env_file:
      - ./.env